<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="./index.css" />
  </head>
  <body>
    <h1>Iframe promise hangs after iframe is destroyed</h1>
    <p>
      This simple repro demonstrates an unexpected "frozen-promise" behavior that occurs when code calls a long-running
      iframe function, and the iframe is destroyed before the function completes.
    </p>
    <p>
      Our expectation is that if the "outside" window calls something on the iframe and gets a `Promise` returned, that
      `Promise` should either resolve or reject, but it shouldn't just hang indefinitely. If the iframe is destroyed and
      all code stops executing on the iframe -- which seems to be the case -- the Promise should reject with some sort
      of "Execution context is destroyed" error.
    </p>
    <p>To see the example yourself:</p>
    <ol>
      <li>
        Click "Invoke iframe function" and wait 2 seconds. You'll see a log statement saying that the iframe execution
        completed:
        <code>Host App: invokeSomethingOnIframe is done</code>
      </li>
      <li>
        Now click "Invoke iframe function" again, but immediately after click "Remove iframe". This time, the
        <code>Host App: invokeSomethingOnIframe is done</code>
        will <b>fail</b> to show up.
      </li>
    </ol>

    <button class="button" disabled="disabled" id="invoke-iframe-function">Invoke iframe function</button>
    <button class="button" disabled="disabled" id="remove-iframe">Remove iframe</button>

    <hr />
    <div id="log"></div>
    <hr />
    <div id="iframe-parent"></div>
    <hr />

    <p>
      The salient code is as follows (the full source can be found
      <a href="https://github.com/Zlatkovsky/HungIframePromise">here</a>)
    </p>

    <h2>Host code</h2>

    <pre>
try {
  console.log("Host App: Starting call to iframe function, this will take 2 seconds");
  await iframe.contentWindow.longRunningIframeFunction();
  console.log("Host App: Finished call to iframe function");
} catch (e) {
  console.error(`Host App: Caught error when executing iframe function. Error was: "${e}"`);
}
console.log("Host App: invokeSomethingOnIframe is done");
</pre
    >

    <h2>Iframe code</h2>
    <pre>
window.longRunningIframeFunction = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log("Iframe: finished waiting 2 seconds, returning the Promise");
      resolve();
    }, 2000);
  });
};  
</pre
    >

    <p>
      Our expectation is that if the "outside" window calls something on the iframe and gets a
      <code>Promise</code> returned, that <code>Promise</code> should either resolve or reject, but it shouldn't just
      hang indefinitely. If the iframe is destroyed and all code stops executing on the iframe -- which seems to be the
      case -- the <code>Promise</code> should reject with some sort of <em>"Execution context is destroyed"</em> error.
    </p>

    <p>
      In our production-app case, the hanging Promise causes cleanup code -- which would otherwise run as soon as the
      Promise is resolved or rejected -- to not run. This, in turn, causes a massive memory leak.
    </p>

    <script src="./index.js"></script>
  </body>
</html>
